### ISSUE TITLE
In the sample, how to set min&max hour?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tobiasschuerg/android-week-view#11]
I'd like to see a full 24 hours instead of a part-day range...

**Comment by tobiasschuerg** [comment]
Currently the height is adjusted based on the events.
Maybe I'll add adjusting min & max manually that at some point

**Comment by AndroidDeveloperLB** [comment]
Does it mean that the more events on the same hour, the larger it gets?

**Comment by tobiasschuerg** [comment]
Yes, it automatically gets larger.

However, when you pass your events as `WeekData`, you can manually override `earliestStart` and `latestEnd` if the automatically determined value doesn't fit your use.

**Comment by AndroidDeveloperLB** [comment]
I see. It makes sense. 
But on Calendar app of Google, there is a way to almost show entire day. It will resize all events.
I don't have many events per day, so I wonder what happens there if there are a lot., though.
