### ISSUE TITLE
Events that end later than 22:59 will "break" the view

### ISSUE THREAD

**Issue by Schriftx** [tobiasschuerg/android-week-view#18]
If there is only 1 event in a week, that ends later than 22:59, it  will cause the view to not have horizontal lines, and labels for the hours. Also the scrollView won't have an end on the bottom.

If there are multiple events in a week, and some of them ends after 22.59 some of them doesn't, then from the start of the one that ends after 22.59 the view will not have background and the vertical scroll stops too soon.

**Comment by tobiasschuerg** [comment]
Problematic part is here:
https://github.com/tobiasschuerg/android-week-view/blob/9779d7aafb31c4bad7cbf58d861a1bb5559f1bdd/library/src/main/java/de/tobiasschuerg/weekview/view/WeekBackgroundView.kt#L207-L209
I think the end time is set to 00:00 instead of 23:59
