### ISSUE TITLE
Clear all events

### ISSUE THREAD

**Issue by Schriftx** [tobiasschuerg/android-week-view#19]
Is there an option to clear all events from the WeekView?

**Comment by tobiasschuerg** [comment]
As `WeekView` is actually a `RelativeLayout` you can simply call [removeAllViews](https://developer.android.com/reference/android/view/ViewGroup.html#removeAllViews()):
```Kotlin
weekView.removeAllViews()
```
However, this will also remove the background, so you more likely want to do somethign like:
```
weekView.removeViews(1, weekView.childCount -1)
```
to keep the background. 

And as a third option, if you only want to remove some views that match a certain criteria, you can just loop over all the child views:
```
for (childIndex in 0 until weekView.childCount) {
    val childView = weekView.getChildAt(childIndex)
    if (childView is EventView) {
        if (childView.event.title.contains("Sports")) {
            weekView.removeView(childView)
        }
    }
}
```
