### ISSUE TITLE
Dependency Installation Error

### ISSUE THREAD

**Issue by moosepaw** [tobiasschuerg/android-week-view#20]
I've added maven { url 'https://jitpack.io' } to the Project build.gradle file under repositories, and then added implementation  'com.github.tobiasschuerg:android-week-view:-SNAPSHOT' in the app build.gradle. 

I was able to get the original repo running ( alamkanak), but I haven't been able to load in any forks of that repo whatsoever. 

I keep getting,

**Failed to resolve: com.github.tobiasschuerg:android-week-view:-SNAPSHOT**

Any pointers to as why this is happening would be much appreciated.

**Comment by tobiasschuerg** [comment]
Hi @moosepaw, seems like either the repository is not correctly or requesting the dependency itself is not working.

Have a look at the documentation on jitpack: https://jitpack.io/#tobiasschuerg/android-week-view/1.5.0

Also, instead of the snapshot version, you might want to specify a concrete version number:
```
implementation 'com.github.tobiasschuerg:android-week-view:1.5.0'
```

**Comment by tobiasschuerg** [comment]
Also the correct package for the snapshot is `'com.github.tobiasschuerg:android-week-view:master-SNAPSHOT'
` - with the branch name.

**Comment by moosepaw** [comment]
The response is much appreciated, somehow the forks began working again. Although now I have an issue with only your repo in which it keeps implementing [this repo](https://github.com/JakeWharton/ThreeTenABP). I'm not sure what's going on but something weird on my end for sure, I will probably just install your repo manually. Thanks again for the response.
