### ISSUE TITLE
Change week on horizontal scroll/swipe

### ISSUE THREAD

**Issue by aamir-gts** [tobiasschuerg/android-week-view#24]
i want more days data but its show current week i want change week on scroll

**Comment by tobiasschuerg** [comment]
Just implement your own touch listener on the `weekView` and change the data to be displayed.

https://github.com/tobiasschuerg/android-week-view/blob/7121f0b5890cb148fad955c857875490a84c449b/app/src/main/java/de/tobiasschuerg/weekview/sample/SampleActivity.kt#L57-L71

https://developer.android.com/develop/ui/views/touch-and-input/gestures/viewgroup
