### ISSUE TITLE
WeekView library with database

### ISSUE THREAD

**Issue by Legacy254** [tobiasschuerg/android-week-view#8]
wow, Great library, 
however I can't really figure out how to connect to a database such that the weekview is populated with data from the database since i'm quite new to kotlin. Could you please share some source code or advise appropriately.Thanks sir

**Comment by tobiasschuerg** [comment]
Hi @Legacy254, sorry for my late reply. If you did not yet find a storage solution I can recomment you to take a look at [Android Room](https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#0).
